name: "publish"

on:
  workflow_dispatch:
  push:
    branches:
      - chore/build

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "configure yarn"
        run: yarn install
