name: "publish"

on:
  push:
    branches:
      - chore/build
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: microsoft

      - name: Setup antlr4
        run: pip install -U pip antlr4-tools

      - name: Configure yarn
        run: yarn install

      - name: Build js files
        run: yarn build

      - name: Prepare for commit to dist branch
        run: |-
          ls -1 | grep -E '^(dist|package.json)$' | xargs rm -r
          cp -r dist .
          rm -r dist
          ls
